# Generated by Django 2.2.4 on 2020-03-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={},
        ),
    ]
